### PR TITLE
Adding a marketplace mode for ttk and including new tests for external URIs

### PR DESCRIPTION
**Pull request by raosuhas**
This PR does 2 things : 

- Adds a marketplace mode for ttk. This allows us to run the tests in a mode that reduces some of the warnings to errors so that some of the cases that are not relevant for marketplace can be made optional.

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@raosuhas - can you separate these into 2 PRs?  One for the new tests and one for the new mode?

**Comment by bmoore-msft** [comment]
@StartAutomating - can you take a look at the one for the new mode?  I think we might have a simpler way to do it?

**Comment by raosuhas** [comment]
Ok .. I am keeping this as the PR for adding the mode. Will submit a separate one for the test. 

---
In reply to: [1022698082](https://github.com/Azure/arm-ttk/pull/575#issuecomment-1022698082) [](http://example.com/codeflow?ancestors=1022698082,1022698082)

**Comment by raosuhas** [comment]
Let me know if there is a simpler way. Unfortunately the decision where the tests is to be made into a error or warning is only done by the Write-Error Command which is why i needed to abstract that away

---
In reply to: [1023698536](https://github.com/Azure/arm-ttk/pull/575#issuecomment-1023698536) [](http://example.com/codeflow?ancestors=1023698536,1023698536)

**Pull request closed without merging**
