### PR TITLE
added update check

### PR DESCRIPTION
**Pull request by bmoore-msft**

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@StartAutomating

**Comment by StartAutomating** [comment]
@bmoore-msft : I'd do this in the module load.  Putting it in each Test-AzTemplate would -a- be slow and -b- skew metrics.

**Comment by bmoore-msft** [comment]
Ah, yes...  good idea...  how would we do that? ;)

**Comment by StartAutomating** [comment]
@bmoore-msft looks like you've got it in the right place now.

**Pull request merged**
