### PR TITLE
Support for Inner templates

### LINKED ISSUE #49: need to account for running tests in nested deployments with scope "inner"
if the expression eval scope is "inner" for a nested deployment, some of the tests won't work properly ( like variable/param not being used) - need to take a inventory of tests to see which need special handling and which do not.

### LINKED ISSUE #139: VM-Images-Should-Use-Latest-Version is still commented out

### PR DESCRIPTION
**Pull request by StartAutomating**
Should fix #49 
May automatically fix #139 #156 #271

### CODE REVIEW

**Review by bmoore-msft — CHANGES_REQUESTED** [review]
1) Add some specific tests (in the other unit tests) for nested, inner and outer.  Can essentially duplicate some of the existing test cases as a nested template test case

2) when reporting the error, ideal is to have the line number in the original source that exhibits the error (e.g. line 12+1 (which we're report and the sum (13))

3) we may want to highlight that we are switching to an inner template context but only if this adds something actionable for the user

**Comment by bmoore-msft** [comment]
@VeraBE - can you take a look at this one and make sure it's not going to impact what you consume - there are some output changes.

@StartAutomating can help with any questions...

**Comment by VeraBE** [comment]
@bmoore-msft Thank you for the heads up :) I checked and everything seems to be working properly with this branch

**Comment by bmoore-msft** [comment]
Cool - thx for the look...

**Pull request merged**
